apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mar20-pub-1 
  janus-idp.io/tekton: mar20-pub-1
  backstage.io/kubernetes-id: mar20-pub-1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mar20-pub-1
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  